baseURL = "https://som-vezzo.me/"
languageCode = "pt-br"
title = "SomVezzo"
subtitle = "Compositor • Programador"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"